stages:
  - build

image: docker:latest

before_script:
  - docker info
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  tags:
    - integration
  script:
    - docker build -t $CI_REGISTRY_IMAGE:latest -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA -f standalone-deploy/Dockerfile . 
    - docker push $CI_REGISTRY_IMAGE --all-tags
