image: python:3.8-alpine

pages:
  stage: deploy
  script:
  - apk add --update --no-cache make subversion
  - pip install -r requirements.txt
  - make publish
  artifacts:
    paths:
    - public/
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'

test:
  stage: test
  script:
  - apk update && apk add make
  - pip install -r requirements.txt
  - make publish
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
